export * from '../pages/Register/Register'
export * from '../pages/Posted-News/Posted-News'
export * from '../pages/Login/Login'
export * from '../pages/Rent/Rent'
export * from '../pages/Info/Info'
export * from '../pages/Request-News/Request-News'
export * from '../pages/Home/Home'
export * from '../pages/Find-House/Find-House'